# Generated by Django 3.1.5 on 2021-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
